### ISSUE TITLE
facing the below issue in this file.

### ISSUE THREAD

**Issue by Rahul-kAgrawal** [copiousfreetime/mp4parser#1]
(Error at line # 40: The constructor IsoFile(FileChannel) is undefined)
IsoFile isoFile = new IsoFile((fileInputStream.getChannel());
//                isoFile = new IsoFile(Channels.newChannel(new FileInputStream(this.filePath)));
//                Path path = new Path(isoFile);
// ERROR at line # 43: The method getPath(Box, String) from the type Path is not visible
                XmlBox xmlBox = (XmlBox) Path.getPath(isoFile, "/moov/meta/xml ");

**Comment by copiousfreetime** [comment]
@Rahul-kAgrawal This repo is an old snapshot of the one on google code. The most up to date repo for mp4parser is https://github.com/sannies/mp4parser which is what you should probably be using.
