### ISSUE TITLE
facing issue in import module in android Studio

### ISSUE THREAD

**Issue by arindam9851** [copiousfreetime/mp4parser#3]
while run the application it gives the runtime error

Error: Interface com.coremedia.iso.boxes.sampleentry.SampleEntry(classpath class) used as super class of com.coremedia.iso.boxes.sampleentry.SubtitleSampleEntry.

Caused by: com.android.builder.dexing.DexArchiveBuilderException: Failed to process C:\Users\lenovo\AndroidStudioProjects\Skylab-Droid\library\build\intermediates\intermediate-jars\staging\classes.jar

**Comment by copiousfreetime** [comment]
Hi @arindam9851 This is an old fork of the pre-github-migration mp4parser from google code. You really should be looking at https://github.com/sannies/mp4parser instead. This repo is not kept up to date.
